package com.akkafun.w5.payslip.model;

// Generated 2013-3-11 16:58:30 by Hibernate Tools 3.6.0

import com.akkafun.w5.common.model.BusinessData;
import com.akkafun.w5.common.model.Operator;
import com.akkafun.w5.permission.model.Permission;
import com.akkafun.w5.permission.model.Role;
import com.akkafun.w5.user.model.User;
import org.hibernate.Hibernate;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

import javax.validation.constraints.Size;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Payslip implements java.io.Serializable,
        com.akkafun.platform.common.dao.Entity<Long>, BusinessData{

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private Long id;

    private int year;

    private int month;

    private Double coachHour;

    private Double coachSalary;

    private Double adjustSalary;

    private Double actualSalary;

    private String remark;

    private PayslipStatus status;

    private Double balanceBefore;

    private Double balanceAfter;

    private Long userId;

    private User user;

    private Operator operator;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getYear() {
        return year;
    }

    public void setYear(int year) {
        this.year = year;
    }

    public int getMonth() {
        return month;
    }

    public void setMonth(int month) {
        this.month = month;
    }

    public Double getCoachHour() {
        return coachHour;
    }

    public void setCoachHour(Double coachHour) {
        this.coachHour = coachHour;
    }

    public Double getCoachSalary() {
        return coachSalary;
    }

    public void setCoachSalary(Double coachSalary) {
        this.coachSalary = coachSalary;
    }

    public Double getAdjustSalary() {
        return adjustSalary;
    }

    public void setAdjustSalary(Double adjustSalary) {
        this.adjustSalary = adjustSalary;
    }

    public Double getActualSalary() {
        return actualSalary;
    }

    public void setActualSalary(Double actualSalary) {
        this.actualSalary = actualSalary;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public PayslipStatus getStatus() {
        return status;
    }

    public void setStatus(PayslipStatus status) {
        this.status = status;
    }

    public Double getBalanceBefore() {
        return balanceBefore;
    }

    public void setBalanceBefore(Double balanceBefore) {
        this.balanceBefore = balanceBefore;
    }

    public Double getBalanceAfter() {
        return balanceAfter;
    }

    public void setBalanceAfter(Double balanceAfter) {
        this.balanceAfter = balanceAfter;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public Operator getOperator() {
        return operator;
    }

    public void setOperator(Operator operator) {
        this.operator = operator;
    }
}
