package com.akkafun.w5.common.model;

// Generated 2013-3-12 9:05:01 by Hibernate Tools 3.6.0

import java.util.Date;

import com.akkafun.w5.user.model.User;

/**
 * Operator generated by hbm2java
 */
public class Operator implements java.io.Serializable,
		com.akkafun.platform.common.dao.Entity<Long> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Date addTime;
	private Date updateTime;
	private String type;
	
	// 创建人
	private Long creatorId;
	private User creator;
	
	// 更新人
	private Long updatorId;
	private User updator;


	public Long getCreatorId() {
		return this.creatorId;
	}

	public void setCreatorId(Long creatorId) {
		this.creatorId = creatorId;
	}

	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	public Long getUpdatorId() {
		return this.updatorId;
	}

	public void setUpdatorId(Long updatorId) {
		this.updatorId = updatorId;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getCreator() {
		return creator;
	}

	public void setCreator(User creator) {
		this.creator = creator;
	}

	public User getUpdator() {
		return updator;
	}

	public void setUpdator(User updator) {
		this.updator = updator;
	}

}
