package com.akkafun.w5.order.model;

// Generated 2013-3-11 16:58:30 by Hibernate Tools 3.6.0

import com.akkafun.w5.common.model.BusinessData;
import com.akkafun.w5.common.model.Operator;
import com.akkafun.w5.user.model.User;

import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class OrderBase implements java.io.Serializable,
        com.akkafun.platform.common.dao.Entity<Long>, BusinessData{

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    private Long id;

    private Long coachId;

    private User coach;

    private Long customerId;

    private User customer;

    private String customerUsername;

    private String coachUsername;

    private Double price;

    private Date startTime;

    private Date endTime;

    private Double coachHour;

    private Double coachSalary;

    private String remark;

    private OrderStatus status;

    private Operator operator;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCoachId() {
        return coachId;
    }

    public void setCoachId(Long coachId) {
        this.coachId = coachId;
    }

    public User getCoach() {
        return coach;
    }

    public void setCoach(User coach) {
        this.coach = coach;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public User getCustomer() {
        return customer;
    }

    public void setCustomer(User customer) {
        this.customer = customer;
    }

    public String getCustomerUsername() {
        return customerUsername;
    }

    public void setCustomerUsername(String customerUsername) {
        this.customerUsername = customerUsername;
    }

    public String getCoachUsername() {
        return coachUsername;
    }

    public void setCoachUsername(String coachUsername) {
        this.coachUsername = coachUsername;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    public Double getCoachHour() {
        return coachHour;
    }

    public void setCoachHour(Double coachHour) {
        this.coachHour = coachHour;
    }

    public Double getCoachSalary() {
        return coachSalary;
    }

    public void setCoachSalary(Double coachSalary) {
        this.coachSalary = coachSalary;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public OrderStatus getStatus() {
        return status;
    }

    public void setStatus(OrderStatus status) {
        this.status = status;
    }

    public Operator getOperator() {
        return operator;
    }

    public void setOperator(Operator operator) {
        this.operator = operator;
    }
}
