package com.akkafun.w5.permission.model;

// Generated 2013-3-12 9:17:45 by Hibernate Tools 3.6.0

/**
 * RolePermission generated by hbm2java
 */
public class RolePermission implements java.io.Serializable,
		com.akkafun.platform.common.dao.Entity<Long> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private Long roleId;
	private Long permissionId;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Long getRoleId() {
		return roleId;
	}
	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}
	public Long getPermissionId() {
		return permissionId;
	}
	public void setPermissionId(Long permissionId) {
		this.permissionId = permissionId;
	}


}
