package com.akkafun.w5.code.model;

import java.util.List;

import org.apache.commons.lang3.StringUtils;

import com.akkafun.w5.common.Constants;


// Generated 2013-3-23 11:34:39 by Hibernate Tools 3.6.0

/**
 * PubCode generated by hbm2java
 */
public class Code implements java.io.Serializable,
		com.akkafun.platform.common.dao.Entity<Long>, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private Long id;
	private String name;
	private String displayName;
	private String kind;
	private String value;
	private String description;
	private boolean updatable = true;
	private boolean deletable = true;
	private String path;
	private boolean selectable = true;
	
	private List<Code> children;
	
	private Code parent;

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isUpdatable() {
		return this.updatable;
	}

	public void setUpdatable(boolean updatable) {
		this.updatable = updatable;
	}

	public boolean isDeletable() {
		return this.deletable;
	}

	public void setDeletable(boolean deletable) {
		this.deletable = deletable;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public boolean isSelectable() {
		return selectable;
	}

	public void setSelectable(boolean selectable) {
		this.selectable = selectable;
	}

	@Override
	public Object clone(){
		Code code = new Code();
		code.setId(id);
		code.setDescription(description);
		code.setDisplayName(displayName);
		code.setKind(kind);
		code.setName(name);
		code.setValue(value);
		code.setDeletable(isDeletable());
		code.setUpdatable(isUpdatable());
		code.setPath(getPath());
		code.setSelectable(isSelectable());
		code.setChildren(getChildren());
		code.setParent(getParent());
		return code;
	}

	public List<Code> getChildren() {
		return children;
	}

	public void setChildren(List<Code> children) {
		this.children = children;
	}

	public Code getParent() {
		return parent;
	}

	public void setParent(Code parent) {
		this.parent = parent;
	}
	
	/**
	 * 得到这个code在树中的深度
	 * @return
	 */
	public int getDepth() {
		return StringUtils.countMatches(path, Constants.PATH_DELIMITER) + 1;
	}
}
